# LAB 3.2 - Low level `tensorflow`

In [2]:
!pip install tensorflow==2.15

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.2/475.2 MB 1.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 59.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 51.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 71.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.0/442.0 kB 31.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 7.3 MB/s eta 0:00:00
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.16.0
    Uninstalling wrapt-1.16.0:
      Successfully uninstalled wrapt-1.16.0
  Attempting uninstall: ml-dtypes
    Found existing installation: ml-dtypes 0.4.0
    Uninstalling ml-dtypes-0.4.0:
      Successfully uninstalled ml-dtypes-0.4.0
  Attempting uninstall: keras
    Found existing installation: keras 3.4.1
    Uninstalling keras-3.4.1:
      Successfully uninstalled keras-3.4.1
  Attempting uninstall: tensorboard
    Found existing installation

In [1]:
!wget -nc --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/2021.deeplearning/main/content/init.py
import init; init.init(force_download=False);

replicating local resources


In [30]:
from local.lib.rlxmoocapi import submit, session
import inspect
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L03.02", varname="student");

logging in as jader.caro@udea.edu.co ... please wait

-------------
using course session 2021.deeplearning::udea.20242
success!! you are logged in
-------------


In [4]:
import numpy as np
import os
import tensorflow as tf
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Dense, BatchNormalization

tf.__version__

'2.15.0'

## TASK 1: Obtain layer output


**COMPLETE** the following function so that, when given a TF `model` and input  `X` returns the output of the model at layer `layer_name` when feeding `X` to the model.


You **MUST RETURN** a `numpy` array, **NOT** a tensor.

**HINT**: Use the [`tf.keras.Model`](https://www.tensorflow.org/api_docs/python/tf/keras/Model) class like in the functional API with `outputs` from the desired layer.

**CHALLENGE**: Solve it with a single line of code (not counting the `import`)

In [20]:
def output_at_layer(X, model, layer_name):
    from tensorflow.keras.models import Model
    r = (Model(inputs=model.inputs, outputs=model.get_layer(layer_name).output)(X))

    return r.numpy()

check your answer manually. With the following model and weights below you should get this answer:


        >> output_at_layer(X, model, "layer_A")
        array([[0.91274303, 0.69886017, 0.8832942 ],
               [0.9311633 , 0.7634138 , 0.8924969 ],
               [0.85661894, 0.5696809 , 0.8091405 ],
               [0.8952345 , 0.6803274 , 0.8326857 ]], dtype=float32)

        >> output_at_layer(X, model, "layer_B")
        array([[0.87063193, 0.8240411 ],
               [0.8774254 , 0.83376545],
               [0.84875023, 0.7963983 ],
               [0.86286545, 0.81590414]], dtype=float32)

        >> output_at_layer(X, model, "layer_C")
        array([[0.8959839 , 0.65980244],
               [0.9032545 , 0.66435313],
               [0.8733646 , 0.646801  ],
               [0.8883195 , 0.6559416 ]], dtype=float32)

In [21]:
def get_model(n1,n2,n3):
    model = Sequential()
    model.add(Dense(n1, name="layer_A", activation="tanh", input_dim=2))
    model.add(Dense(n2, name="layer_B", activation="sigmoid"))
    model.add(Dense(n3, name="layer_C", activation="linear"))
    return model


w = [np.array([[0.3336241 , 0.26024526, 0.37238857],
               [0.6344426 , 0.67660165, 0.31070882]], dtype=np.float32),
     np.array([0.97280777, 0.3447949 , 0.91722184], dtype=np.float32),

     np.array([[0.12999585, 0.31851983],
               [0.7763866 , 0.8777575 ],
               [0.99977154, 0.65771514]], dtype=np.float32),
     np.array([0.36222705, 0.05885772], dtype=np.float32),

     np.array([[0.75918376, 0.02541249],
               [0.21730722, 0.45021895]], dtype=np.float32),
     np.array([0.05594416, 0.26667854], dtype=np.float32)]


X = np.array([[0.9269997 , 0.41239464],
              [0.8461177 , 0.64935404],
              [0.27092433, 0.34251866],
              [0.22509325, 0.6301328 ]], dtype=np.float32)


model=get_model(3,2,2)
model.set_weights(w)

In [22]:
output_at_layer(X, model, "layer_A")

array([[0.91274303, 0.69886017, 0.8832942 ],
       [0.9311633 , 0.7634138 , 0.8924969 ],
       [0.85661894, 0.5696809 , 0.8091405 ],
       [0.8952345 , 0.6803274 , 0.8326857 ]], dtype=float32)

In [23]:
# which corresponds to a tanh activation from the input data
np.tanh(X.dot(w[0])+w[1])

array([[0.912743  , 0.69886017, 0.8832942 ],
       [0.9311633 , 0.7634138 , 0.89249694],
       [0.8566189 , 0.5696809 , 0.8091404 ],
       [0.89523464, 0.6803274 , 0.8326857 ]], dtype=float32)

In [24]:
output_at_layer(X, model, "layer_B")

array([[0.87063193, 0.8240411 ],
       [0.8774253 , 0.83376545],
       [0.84875023, 0.7963982 ],
       [0.8628655 , 0.81590414]], dtype=float32)

In [25]:
# which corresponds to a sigmoid activation from the output of layer A
sigm = lambda x: 1/(1+np.exp(-x))
sigm(output_at_layer(X, model, "layer_A").dot(w[2])+w[3])


array([[0.870632  , 0.8240412 ],
       [0.8774254 , 0.8337655 ],
       [0.8487503 , 0.7963983 ],
       [0.86286545, 0.81590414]], dtype=float32)

In [26]:
output_at_layer(X, model, "layer_C")

array([[0.8959839 , 0.6598024 ],
       [0.90325445, 0.66435313],
       [0.8733646 , 0.646801  ],
       [0.8883195 , 0.6559416 ]], dtype=float32)

In [27]:
# which corresponds to a linear activation from the output of layer B
output_at_layer(X, model, "layer_B").dot(w[-2])+w[-1]

array([[0.8959839 , 0.65980244],
       [0.90325445, 0.66435313],
       [0.8733646 , 0.646801  ],
       [0.8883195 , 0.6559416 ]], dtype=float32)

**Registra tu solución en linea**

In [28]:
student.submit_task(namespace=globals(), task_id='T1');

## TASK 2: Implement batch normalization

Observe how we create a **ONE LAYER** model with **TANH** activation and batch normalization

In [29]:
def get_model(input_dim, n):
    model = Sequential()
    model.add(Dense(n, name="layer_A", activation="tanh", input_dim=input_dim))
    model.add(BatchNormalization())
    return model

we manually initialize it with random weights and apply it to some random input

In [31]:

input_dim = np.random.randint(3)+2
n = np.random.randint(5)+5
X = np.random.random((6,input_dim)).astype(np.float32)
print ("input_dim", input_dim, ", n", n)


input_dim 4 , n 9


In [32]:

model = get_model(input_dim=input_dim, n=n)
model.set_weights([np.random.random(i.shape) for i in model.get_weights()])
model(X).numpy()


array([[1.5382261 , 1.3265887 , 0.2111901 , 0.36914372, 2.0840259 ,
        1.140213  , 0.24507023, 1.0803568 , 0.82778794],
       [1.452389  , 1.3293067 , 0.11735171, 0.35539216, 1.9975845 ,
        1.0746243 , 0.24266517, 1.1120584 , 0.80703455],
       [1.5988474 , 1.4587266 , 0.33320588, 0.3850316 , 2.4470866 ,
        1.2495728 , 0.25779265, 1.2041446 , 0.85085356],
       [1.5210712 , 1.3932866 , 0.25162673, 0.37837717, 2.269963  ,
        1.1518137 , 0.24739791, 1.1540163 , 0.832158  ],
       [1.5248473 , 1.442284  , 0.25165474, 0.38240117, 2.3853796 ,
        1.2128164 , 0.25478444, 1.2000061 , 0.8357644 ],
       [1.5056195 , 1.3900074 , 0.22945589, 0.38303113, 2.318078  ,
        1.1686976 , 0.24893695, 1.1732727 , 0.8222252 ]], dtype=float32)

and we can extract the weights of the dense layer and the batch normalization layer

In [33]:

W, b, gamma, beta, moving_mean, moving_var = model.get_weights()
W.shape, b.shape, beta.shape, moving_mean.shape, moving_var.shape


((4, 9), (9,), (9,), (9,), (9,))

**COMPLETE** the following function **WITHOUT USING TENSORFLOW** such that you get the same output as the model above, given the input and the weights.

In specific, the Dense layer output must be

$$A = \text{tanh}(XW+b)$$

And the batch normalization layer after that output is

$$\frac{A-m_\mu}{\sqrt{m_\sigma+\varepsilon}}\gamma + \beta$$

You **MUST RETURN** a `numpy` array, **NOT** a tensor.

**CHALLENGE**: Solve it with one single line of Python code.

In [34]:
def apply_model(X, W, b, gamma, beta, moving_mean, moving_var, epsilon=1e-3):
    A = np.tanh(X.dot(W)+b)
    return (A-moving_mean)/(np.sqrt(moving_var+epsilon)) * gamma + beta

check manually your code, the output should be the same as above.

In [35]:
apply_model(X, W, b, gamma, beta, moving_mean, moving_var)

array([[1.5382259 , 1.3265886 , 0.21119009, 0.36914372, 2.0840263 ,
        1.140213  , 0.24507023, 1.0803568 , 0.82778794],
       [1.452389  , 1.3293066 , 0.11735165, 0.35539216, 1.9975845 ,
        1.0746243 , 0.24266516, 1.1120584 , 0.8070346 ],
       [1.5988472 , 1.4587265 , 0.333206  , 0.38503158, 2.447087  ,
        1.2495726 , 0.25779265, 1.2041447 , 0.8508534 ],
       [1.521071  , 1.3932866 , 0.25162667, 0.37837717, 2.2699633 ,
        1.1518139 , 0.2473979 , 1.1540163 , 0.8321579 ],
       [1.5248469 , 1.4422841 , 0.2516547 , 0.38240123, 2.38538   ,
        1.2128165 , 0.25478444, 1.2000062 , 0.83576435],
       [1.5056194 , 1.3900073 , 0.22945595, 0.38303113, 2.3180785 ,
        1.1686977 , 0.24893695, 1.1732728 , 0.8222251 ]], dtype=float32)

**Registra tu solución en linea**

In [36]:
student.submit_task(namespace=globals(), task_id='T2');

## TASK 3: Compute the Hessian

Complete the function below so that computes the Hessian of a function with respect to a set of variables. Remember that the Hessian is the matrix with all combinations of double partial derivatives. See [https://en.wikipedia.org/wiki/Hessian_matrix](https://en.wikipedia.org/wiki/Hessian_matrix)


The arguments for your code below:

- `expression_fn`: is a Python function that, when executed, will return a Tensor depending on the variables in `svars`.
- `svars`: a list of $n$ `tf.Variable`s against which  the derivatives are to be taken.

The result:

- a `numpy` array of dimension $n\times n$, containing in each position the value of the corresponding double derivative evaluated with the value attached to each variable in `svars`.

See the example call below to understand what you have to produce.

**NOTE**: Observe that `expression_fn` is a function that you **must call** inside some `GradientTape` to obtain the expresion. This needs to be done this way because `GradientTape` needs to _watch_ how expressions are built to be able to access the computational graph and compute the gradient. This is a technique which is very often used in Tensorflow.



**WARN**: You cannot use `tf.hessian` or `GradientTape.jacobian` or `sympy`. Do not use the name `hessian` to name any variable within your code.

**HINT 1**: use a `GradientTape` inside another `GradientTape`.

**HINT 2**: use `unconnected_gradients=tf.UnconnectedGradients.ZERO` as argument to `GradientTape.gradient` to have the variables not participating in an expresion result in gradient zero. For instance with $f=xy$, we have $\frac{\partial f}{\partial y\partial y}=0$, since $\frac{\partial f}{\partial y}=1$. Or if we have $f=x$ we have $\frac{\partial f}{\partial y\partial x}=0$, since $\frac{\partial f}{\partial y}=0$. If you do not include this argument, Tensorflow will return these values as `None` and you would have to fix them later.

In [ ]:
def get_double_derivatives(expression_fn,svars):
    import tensorflow as tf

    result = ...

    return result


In [75]:
def get_double_derivatives(expression_fn,svars):
    import tensorflow as tf
    import numpy as np

    with tf.GradientTape(persistent=True) as tape1:
        tape1.watch(svars)
        with tf.GradientTape() as tape2:
            tape2.watch(svars)
            result = expression_fn()
        grads = tape2.gradient(result, svars, unconnected_gradients=tf.UnconnectedGradients.ZERO)
    hs = []
    for grad in grads:
        hs.append(tape1.gradient(grad, svars, unconnected_gradients=tf.UnconnectedGradients.ZERO))
    del tape1
    return np.array([[h.numpy() for h in hs_row] for hs_row in hs])

check your code. The following expression

$$f = 2xy^2 + 3x\cos{y}$$

has as first derivatives:

- $\frac{\partial f }{\partial x} = 2y^2 +3\cos{y}$
- $\frac{\partial f }{\partial y} = 4xy - 3x\sin{y}$

and as second derivatives:

- $\frac{\partial f }{\partial x \partial x} = 0$
- $\frac{\partial f }{\partial x \partial y} = 4y - 3\sin{y}$
- $\frac{\partial f }{\partial y \partial x} = 4y - 3\sin{y}$
- $\frac{\partial f }{\partial y \partial y} = 4x - 3x\cos{y}$

which, when evaluated at $x=2$ and $y=-3$ yields

    [[  0     ,  -11.58],
     [ -11.58 ,   13.94]]

In [76]:
x = tf.Variable(2, dtype=tf.float32)
y = tf.Variable(-3, dtype=tf.float32)
expr = lambda: 2*x*y**2 + 3*x*tf.cos(y)

get_double_derivatives(expr, [x,y])

array([[  0.      , -11.57664 ],
       [-11.57664 ,  13.939955]], dtype=float32)

**Registra tu solución en linea**

In [77]:
student.submit_task(namespace=globals(), task_id='T3');